name: Purge Cache

on:
  push:
    branches: [ master, preview ]
  workflow_dispatch:

jobs:
  pruge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Send Purge Request
        run: node .github/scripts/purge-cache.js
