name: Stale Bot

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 1 day.'
        stale-pr-message: 'This pull request is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 1 day.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-label: long-term
        exempt-pr-label: long-term
        days-before-stale: 180
        days-before-close: 1
